### ISSUE TITLE
配置文件域验证问题

### ISSUE THREAD

**Issue by 5high** [Equim-chan/h2s#2]
{
	"bind": "127.0.0.1:8088",
	"upstreams": [{
		"address": "10.14.1.10:8080",
		"username": "domain\### m",
		"password": "password"
	}],
	"timeout": "20s",
	"retries": 3
}

使用这个配置文件会报一下错误

2018/07/25 16:20:54.767080 parse config: invalid character 'm' in string escape code

因为用户名第一位是m开头

**Comment by 5high** [comment]
OMG，domian\m自动变成###

**Comment by Equim-chan** [comment]
试一下 `"username": "domain\\m"`
