### ISSUE TITLE
V2ray+WS+TLS配置文件排错

### ISSUE THREAD

**Issue by 5high** [Equim-chan/h2s#3]
我这个配置文件昨天还可以用，今天就不能正常使用了，非常奇怪。

Vray

{
	"inbound": {
		"port": 1080,
		"listen": "0.0.0.0",
		"protocol": "socks",
		"settings": {
			"auth": "noauth",
			"udp": true
		}
	},

	"outbound": {
		"mux": {
			"enabled": true
		},
		"protocol": "vmess",
		"settings": {
			"vnext": [{
				"address": "127.0.0.1",
				"port": 50001,
				"users": [{
					"id": "UUID",
					"alterId": 64
				}]
			}]
		},
		"streamSettings": {
			"network": "ws",
			"security": "tls",
			"tlsSettings": {
				"serverName": "xxx.com"
			},
			"wsSettings": {
				"path": "/path",
				"headers": {
					"Host": "xxx.com"
				}
			}
		}
	},

	"inboundDetour": [{
		"domainOverride": ["tls", "http"],
		"listen": "127.0.0.1",
		"port": 50001,
		"protocol": "dokodemo-door",
		"settings": {
			"address": "xxx.com",
			"port": 443
		},
		"tag": "内部桥接点"
	}],

	"outboundDetour": [{
			"protocol": "socks",
			"settings": {
				"servers": [{
					"address": "127.0.0.1",
					"port": 1088
				}]
			},
			"tag": "h2s"
		}
	],
	"routing": {
		"settings": {
			"rules": [{
					"type": "field",
					"inboundTag": ["内部桥接点"],
					"outboundTag": "h2s"
				}
			],
			"domainStrategy": "IPIfNonMatch"
		},
		"strategy": "rules"
	}

}

H2S

{
	"bind": "127.0.0.1:1088",
	"upstreams": [{
		"address": "192.168.99.100:9092"
	}],
	"timeout": "20s",
	"retries": 3
}

**Comment by Equim-chan** [comment]
有日志吗？

**Comment by 5high** [comment]
好像流量都没有送到v2ray,下面是H2S的日志

2018/07/27 09:22:19.167278 Listening on 127.0.0.1:1088
2018/07/27 09:22:46.808950 h2s: handshake upstream: unexpected EOF
2018/07/27 09:22:46.858080 h2s: handshake upstream: unexpected EOF
2018/07/27 09:22:49.228207 h2s: handshake upstream: unexpected EOF
2018/07/27 09:22:49.233203 h2s: handshake upstream: unexpected EOF
2018/07/27 09:22:49.234193 h2s: handshake upstream: unexpected EOF
2018/07/27 09:22:54.237469 h2s: handshake upstream: unexpected EOF
2018/07/27 09:22:59.212672 h2s: handshake upstream: unexpected EOF
2018/07/27 09:23:07.849880 h2s: handshake upstream: unexpected EOF
2018/07/27 09:23:07.894012 h2s: handshake upstream: unexpected EOF
2018/07/27 09:23:10.261316 h2s: handshake upstream: unexpected EOF
2018/07/27 09:23:10.268302 h2s: handshake upstream: unexpected EOF
2018/07/27 09:23:10.269303 h2s: handshake upstream: unexpected EOF
2018/07/27 09:23:15.266286 h2s: handshake upstream: unexpected EOF
2018/07/27 09:23:20.244102 h2s: handshake upstream: unexpected EOF

**Comment by 5high** [comment]
不好意思，这个配置文件没问题，我用错了端口，使用V2RAY的inbound 1080端口就没问题了。

**Comment by 5high** [comment]
但是如果http proxy是NTLM认证H2S会报407错误
