### ISSUE TITLE
与上游握手失败

### ISSUE THREAD

**Issue by ghost** [Equim-chan/h2s#9]
您好,我想将学校提供的https代理转变为socks5代理,结果抛出了下面异常:
2019/03/08 10:28:25.489871 Listening on 127.0.0.1:2333
2019/03/08 10:28:34.606348 h2s: serve: handshake upstream: unexpected EOF
2019/03/08 10:28:34.632784 h2s: serve: handshake upstream: unexpected EOF
2019/03/08 10:28:34.635032 h2s: serve: handshake upstream: unexpected EOF
2019/03/08 10:28:34.639377 h2s: serve: handshake upstream: unexpected EOF
2019/03/08 10:28:34.641627 h2s: serve: handshake upstream: unexpected EOF
2019/03/08 10:28:34.750934 h2s: serve: handshake upstream: unexpected EOF
2019/03/08 10:28:34.759173 h2s: serve: handshake upstream: unexpected EOF
2019/03/08 10:28:39.803129 h2s: serve: handshake upstream: unexpected EOF
2019/03/08 10:28:39.810537 h2s: serve: handshake upstream: unexpected EOF
2019/03/08 10:28:55.044235 h2s: serve: handshake upstream: unexpected EOF
2019/03/08 10:28:55.050157 h2s: serve: handshake upstream: unexpected EOF
配置文件为:
{                                                        
  "bind": "127.0.0.1:2333",                              
                                                         
  "upstreams": [{                                        
    "address": "scholar-proxy.proxy.cn:3128",         
                                                         
                                                         
    "username": "username",                               
    "password": "passwd"                               
                                                         
  }],                                                    
                                                         
                                                         
  "timeout": "20s",                                      
  "retries": 3                                           
} 
我在wsl中使用H2S,然后在win下使用switchyomega 连接socks代理,        switchyomega填入127.0.0.1:2333
请问该怎么解决呢?万分感谢!

**Comment by ghost** [comment]
在Ubuntu会serve: handshake upstream: read tcp 172.31.206.250:44386->10.8.8.6:3128: read: connection reset by peer

**Comment by Equim-chan** [comment]
上游可能有额外的防火墙设定？

**Comment by phantomedc** [comment]
同样与上游握手失败，日志内容
`h2s: serve: handshake upstream: 503 Service Unavailable` 

但是我用ssr，将公司代理设置为前置代理时，ssr是work的，v2ray+h2s就不行
h2s 配置文件内容：
`{
  "bind": "127.0.0.1:1081",
  "upstreams": [{
    "address": "xxx.xxx.com:8080"
  }
],
  "timeout": "20s",
  "retries": 3
}`
